apiVersion: v2
name: php-guest-book
description: A Helm chart for the php guest book.
version: 0.1.1
appVersion: "5.0.0"
home: https://github.com/kubernetes/examples/tree/master/guestbook
icon: http://clipart-library.com/images_k/php-logo-transparent/php-logo-transparent-17.png
keywords:
  - php
  - guestbook
  - redis
sources:
  - https://github.com/ananware-systems/guestbook-helm
  - https://github.com/sossickd/helm-charts
maintainers:
  - name: sossickd
    email: daniel.sossick@rbi.co.uk
dependencies:
- name: redis
  version: "15.4.*"
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "New chart version 0.1.1"
